/**
 * Liste officielle des 45 communes du canton de Genève
 * Source: République et canton de Genève
 */
export const COMMUNES_GENEVE = [
  'Aire-la-Ville',
  'Anières',
  'Avully',
  'Avusy',
  'Bardonnex',
  'Bellevue',
  'Bernex',
  'Carouge',
  'Cartigny',
  'Céligny',
  'Chancy',
  'Chêne-Bougeries',
  'Chêne-Bourg',
  'Choulex',
  'Collex-Bossy',
  'Collonge-Bellerive',
  'Cologny',
  'Confignon',
  'Corsier',
  'Dardagny',
  'Genève',
  'Genthod',
  'Grand-Saconnex',
  'Gy',
  'Hermance',
  'Jussy',
  'Laconnex',
  'Lancy',
  'Meinier',
  'Meyrin',
  'Onex',
  'Perly-Certoux',
  'Plan-les-Ouates',
  'Pregny-Chambésy',
  'Presinge',
  'Puplinge',
  'Russin',
  'Satigny',
  'Soral',
  'Thônex',
  'Troinex',
  'Vandœuvres',
  'Vernier',
  'Versoix',
  'Veyrier',
] as const;

export type CommuneGeneve = typeof COMMUNES_GENEVE[number];
